### ISSUE TITLE
benchmarks

### ISSUE THREAD

**Issue by mybigman** [tangpanqing/aorm#1]
would like to see some benchmarks against various libraries...

```
sql
sqlx
gorm
bun
squrriel
```

etc

looks interesting though.

thanks

**Comment by tangpanqing** [comment]
hi, thanks for support
i test some lib, the benchmarks report is here
https://github.com/tangpanqing/orm-benchmark

**Comment by tangpanqing** [comment]
hi, thanks for support
i test some lib, the benchmarks report is here
https://github.com/tangpanqing/orm-benchmark

**Comment by tangpanqing** [comment]
@mybigman 

hi, thanks for support
i test some lib, the benchmarks report is here

https://github.com/tangpanqing/orm-benchmark

**Comment by mybigman** [comment]
thanks

**Comment by tangpanqing** [comment]
@mybigman 

hi, here is the new benchmarks test
https://github.com/tangpanqing/orm-benchmark

i just optimize query, the result looks nice

**Comment by mybigman** [comment]
yes... looking much better... well done and thanks.
