### ISSUE TITLE
请问一下有没有根据数据库中的表生成结构体的功能

### ISSUE THREAD

**Issue by duolabmeng6** [tangpanqing/aorm#8]
因为自己定义好麻烦，看了文档没有发现这个功能 不知有没有开发～特地来请教一下

**Comment by tangpanqing** [comment]
> 因为自己定义好麻烦，看了文档没有发现这个功能 不知有没有开发～特地来请教一下

aorm目前没有这个功能，我推荐先定义结构体，然后用结构体去创建和修改表结构。

不过如果你是老项目的话，我看到有其他朋友开发过这样的库，你可以搜索下。

**Comment by duolabmeng6** [comment]
好的 谢谢 因为看到您的库 api 很优雅准备用起来

**Comment by tangpanqing** [comment]
> 好的 谢谢 因为看到您的库 api 很优雅准备用起来

感谢支持。
