### ISSUE TITLE
GetOne 和 GetMany 的 defer 语句提前了

### ISSUE THREAD

**Issue by itviewer** [tangpanqing/aorm#9]
https://github.com/tangpanqing/aorm/blob/76e6fed33014377dac6995914bb3ff4d7f20d062/builder/crud.go#L249
errRows 不等于 nil 的话，rows 为 nil，`defer rows.Close()` 会 panic

```
	rows, errRows := b.GetRows()
	defer rows.Close()
	if errRows != nil {
		return errRows
	}
```
受影响的有 GetOne 和 GetMany 两个函数

**Comment by tangpanqing** [comment]
看上去好像确实会有问题，我试试
